apiVersion: v1
kind: Service
metadata:
  name: rest-starter-svc
  labels:
    app: rest-starter
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: rest-starter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-starter-deployment
  labels:
    app: rest-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-starter
  template:
    metadata:
      labels:
        app: rest-starter
    spec:
      containers:
        - name: rest-starter
          image: rest-starter:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
            requests:
              memory: "16Mi"
              cpu: "50m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rest-starter-hpa
  labels:
    app: rest-starter
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: autoscaling/v1
    kind: Deployment
    name: rest-starter
  targetCPUUtilizationPercentage: 50
