apiVersion: v1
kind: Service
metadata:
  name: starter
  labels:
    app: starter
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: starter
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starter
  template:
    metadata:
      labels:
        app: starter
    spec:
      containers:
        - name: starter
          image: starter:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "32mi"
              cpu: "100m"
            resquests:
              memory: "16Mi"
              cpu: "50m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: starter
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: autoscaling/v1
    kind: Deployment
    name: starter
  targetCPUUtilizationPercentage: 50
