apiVersion: v1
kind: Service
metadata:
  name: rest-starter
  labels:
    app: rest-starter
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30031
      targetPort: 8080
  selector:
    app: rest-starter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rest-starter
data:
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-starter
  labels:
    app: rest-starter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-starter
  template:
    metadata:
      labels:
        app: rest-starter
    spec:
      containers:
        - name: rest-starter
          image: rest-starter:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: rest-starter
                optional: false
            - prefix: GRPC_STARTER_
              configMapRef:
                name: grpc-starter
                optional: false
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "32Mi"
              cpu: "100m"
            requests:
              memory: "16Mi"
              cpu: "50m"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rest-starter
  labels:
    app: rest-starter
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rest-starter
  targetCPUUtilizationPercentage: 50
