version: '3'
services:
  grpc-starter:
    image: grpc-starter
  rest-starter:
    build:
      context: ../
      dockerfile: ./build/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - grpc-starter